language: r
cache: packages
sudo: required
dist: trusty
warnings_are_errors: false

os:
  - linux
  - osx

env:
  global:
    - NOT_CRAN=true
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_BUILD_ARGS="--no-build-vignettes" 
    - R_CHECK_ARGS="--as-cran"
    - BOOTSTRAP_LATEX="1"  

before_install: 
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"
  - echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile
  - curl -OL http://raw.github.com/eddelbuettel/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  
install:
  - ./travis-tool.sh install_aptget r-cran-rcpp libquantlib0-dev r-cran-runit r-cran-rgl littler r-cran-shiny
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  
r_packages:
  - devtools
  - knitr
  - covr
  - rmarkdown
  - testthat
  
after_success:
  - Rscript -e 'covr::codecov()'
 
