# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

sudo: required

global:
- _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
 - sudo apt-get update && sudo apt-get install libhdf5-serial-dev libgdal-dev libproj-dev

r_binary_packages:
- rgdal
- sp
- raster

