# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

sudo: required

#before_install:
#- sudo apt-get install aptitude
#- sudo aptitude install libgdal-dev libproj-dev --assume-yes

global:
- _R_CHECK_FORCE_SUGGESTS_=FALSE

r_binary_packages:
- rgdal
- sp
- raster

